# CICD pipeline for auto deploy of MNP VM web server  infrastructure build and routine management deployments

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: MNPdevops
    subscriptionId: 'ef83523f-8e18-400d-ad8f-3074d3980225'
    resourceGroupName: MNPdevopschallangerg
    location: 'Canada Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/cloudguydev/MNPTechchallange/main/MNP_VMWebserver_template.json'
    deploymentName: mnparmdeploy

